### ISSUE TITLE
 is having the following problem

### ISSUE THREAD

**Issue by leoguimaraes49** [CrimsonSunrise/Blaze-Double-Automator#2]
![image](https://user-images.githubusercontent.com/72119698/188016646-58c48aa2-41dc-4be4-86e7-39149432ac5a.png)

is having the following problem

**Comment by CrimsonSunrise** [comment]
Hey @leogsvm !
Did you tried to install requests manually?

**Comment by leoguimaraes49** [comment]
Yes

**Comment by CrimsonSunrise** [comment]
Can you tell me which version of Requests are you using?
