### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by CentroEducacional-CEC** [CrimsonSunrise/Blaze-Double-Automator#4]
`C:\Users\SERVIDOR\Desktop\Bots\whatsapp-bot-master\src\Blaze>python main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from Automation import Bot
  File "C:\Users\SERVIDOR\Desktop\Bots\whatsapp-bot-master\src\Blaze\Automation.py", line 35
    chrome_options.add_argument(f"user-agent={user_agent}")
                                                         ^
SyntaxError: invalid syntax

C:\Users\SERVIDOR\Desktop\Bots\whatsapp-bot-master\src\Blaze>`

**Comment by CrimsonSunrise** [comment]
You might be using an old version of Python as literal string interpolation was only introduced in Python 3.6.
Make sure you update it or change the string interpolation method to something like the following, should work as fine:
`chrome_options.add_argument("user-agent="+user_agent)`

Let me know if it worked, also if you are indeed using an older version of Python.
